### ISSUE TITLE
OBJ export broken

### ISSUE THREAD

**Issue by ipadjen** [dtcc-platform/dtcc-builder#11]
Hello! I'm opening this issue as a part of the JOSS review: https://github.com/openjournals/joss-reviews/issues/4928

There is a problem with OBJ export. It seems that there are two issues:

1.  The results are rotated 90 degrees over the x-axis.
2.  Normals are flipped for all faces.

Here are the results of the example case HelsingborgResidential and CitySurface in .stl, .vtu, and .obj:

<img src="https://user-images.githubusercontent.com/49401914/228179362-8efb50ed-1c5c-4f44-a3a6-7dd03aefc6b2.png" width="500">
<img src="https://user-images.githubusercontent.com/49401914/228179417-f8a27fb4-f328-4656-8579-a1837c0fdc41.png" width="500">

**Comment by vbassn** [comment]
@ipadjen should be fixed now! Care to double check?

**Comment by ipadjen** [comment]
I gave it a look, this is what I see:
- Face orientations are fixed.
- CitySurface is still 90 degrees rotated, whereas the other .objs are fine. I noticed it might be a design decision due to Blender?
- The results still look different from .stls and vtus. Could it be that vertex normals are still weirdly oriented? OBJ is on the right of the figure.

![obj_comparison](https://user-images.githubusercontent.com/49401914/229870625-85e17f25-70e2-42b9-9c33-caf9a8294ab8.png)

**Comment by vbassn** [comment]
@ipadjen Thanks for this! Checking again with my coauthor @dwastberg

**Comment by vbassn** [comment]
@ipadjen Which viewer are you using for the last screenshot? Is it Paraview?

**Comment by ipadjen** [comment]
Yes, the screenshot is from Paraview. I also checked it in MeshLab and a similar thing -- STL vs OBJ are colored differently.

**Comment by vbassn** [comment]
@ipadjen latest fix should handle everything! The STL now is the basis, and OBJ is a mere internal Assimp transformation, so `WriteSTL` parameter is now obsolete!

**Comment by ipadjen** [comment]
Looks good now!

**Comment by vbassn** [comment]
ok closing this @anderslogg
