### ISSUE TITLE
Handling polygons with holes

### ISSUE THREAD

**Issue by ipadjen** [dtcc-platform/dtcc-builder#12]
Hello,

An issue from the JOSS review: https://github.com/openjournals/joss-reviews/issues/4928

Polygons with holes seem to be ignored: 

![poly_with_holes](https://user-images.githubusercontent.com/49401914/227593874-8ca0c903-3676-46a9-aa85-7094926c3066.png)

**Comment by anderslogg** [comment]
This is a known issue that we are planning to fix in an upcoming release based off the `develop` branch of dtcc-builder which has come a long way since the original submission of the JOSS article/branch.

Is it critical that this issue is fixed for the JOSS submission? @ipadjen

**Comment by anderslogg** [comment]
Yes let's keep it open since we plan to fix this (in a future release).

**Comment by dwastberg** [comment]
Should work with 2d and surface meshes.  Test to make sure it works with volume meshes

**Comment by vbassn** [comment]
@dwastberg I ll have a look for a volume mesh!
