### ISSUE TITLE
Add requirements for point clouds to documentation

### ISSUE THREAD

**Issue by ipadjen** [dtcc-platform/dtcc-builder#13]
Hello, as a part of JOSS review: https://github.com/openjournals/joss-reviews/issues/4928

It would be nice to add few sentences on point cloud requirements to the documentation, more specifically, the information on classification (which classes are necessary, if any).

**Comment by anderslogg** [comment]
Added the following to the docs (usage.md):

> **Note:** The minimal requirement for point cloud data is that
ground points are classified as 2 with other points that are not
ground having a different classification (not 2). If classifications
for buildings (6), vegetation (3-5) and/or water (9) are present,
those are used to potentially improve the city model generation.
