### ISSUE TITLE
An example of a simulation with an input from DTCC-builder

### ISSUE THREAD

**Issue by ipadjen** [dtcc-platform/dtcc-builder#14]
Hello, as a part of JOSS review: https://github.com/openjournals/joss-reviews/issues/4928

It would be nice to show in the paper that grids can be used to run simulations. I think that a grid sensitivity analysis would be good example.

Let me know if you have any other ideas.

**Comment by anderslogg** [comment]
How much of a "real-world" simulation is required?

We can easily add a demo for solving a PDE on the generated meshes to the repository but it may not be a "real-world" case with proper boundary conditions, relevant parameters etc. Such simulations are in progress but require substantial effort to implement and validate. We could add simple demos such as the Stokes equations as a simple model of wind/fluid flow or the Poisson equation as a simple model of electromagnetic fields.

**Comment by ipadjen** [comment]
Just add something that supports the statement from your summary. I think there's also no need for me to wait on you to do that, we can wrap up the review if you agree with that.

**Comment by anderslogg** [comment]
@ipadjen Alright, I'll add a simple PDE demo and point to it in the documentation. Easy to add and should be done this week.

**Comment by anderslogg** [comment]
@ipadjen I have now added a new demo to the repository (the script `demo/dtcc-simulation-demo`). Documentation has also been added on how to run the demo.

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/125354137/235939531-d8dc2820-3b23-4362-b9f4-6498176a813e.png">
