### ISSUE TITLE
Remove extra ClassName: in diagnostic printing

### ISSUE THREAD

**Issue by anderslogg** [dtcc-platform/dtcc-builder#32]
Should be 

`2023-07-07 16:23:02.253 [dtcc-builder] [INFO] Merging buildings...`

instead of

`2023-07-07 16:23:02.253 [dtcc-builder] [INFO] CityBuilder: Merging buildings...`

**Comment by vbassn** [comment]
@anderslogg me and @Georspai we are thinking to keep this as is for debug level and remove for the rest, agreed?

**Comment by Georspai** [comment]
I removed the extra class name printing from all info and warning printing, but not debug. I could do that too but I thought it's useful to know where we're printing from when debugging. 
I can also try to do what Vasilis mentioned above in case we want more details during debugging.

**Comment by anderslogg** [comment]
Looks good! Closing this now.
